---
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - clang
      - cmake
      - gcc
      - libclang-10-dev
      - libclang-dev
      - llvm-dev
      - make
      - rapidjson-dev
    update_cache: yes
  become: true

- name: Get ghq root
  ansible.builtin.command: "ghq root"
  register: ccls_ghq_root
  changed_when: false

- set_fact:
    ccls_repo: "github.com/MaskRay/ccls"

- set_fact:
    ccls_dest: "{{ ccls_ghq_root.stdout }}/{{ ccls_repo }}"

- name: Clone repository
  vars:
    ccls_repo: "github.com/MaskRay/ccls"
  ansible.builtin.git:
    repo: "https://{{ ccls_repo }}"
    dest: "{{ ccls_dest }}"
    version: "0.20220729"
    depth: 1
    recursive: true
  register: ccls_clone_repo

- name: Build
  ansible.builtin.shell: |
    cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_PREFIX_PATH=/usr/lib/llvm-10 \
      -DLLVM_INCLUDE_DIR=/usr/lib/llvm-10/include \
      -DLLVM_BUILD_INCLUDE_DIR=/usr/include/llvm-10/
    cmake --build Release
  args:
    executable: zsh
    chdir: "{{ ccls_dest }}"
    creates: "{{ ccls_dest }}/Release/ccls"

# https://github.com/MaskRay/ccls/wiki/Install#shell-script-wrapper
- name: Create wrapper
  ansible.builtin.template:
    src: "os_elementary_os.bin"
    dest: "{{ ansible_env.HOME }}/bin/ccls"
    mode: "a+x"
