vim.opt.shell = "/bin/bash"    

require "basic"
require "packer_plugins"
require "motion"
require "aesthetic"
require "lsp"
require "completion"
require "comment"
require "explore"
require "format"
require "spell"
require "browser"
require "test"
require "quickfix"
require "git"
require "tf"
require "multi"
