# https://github.com/tfutils/tfenv#manual
---
- name: Create bin directory
  file:
    path: "$HOME/bin"
    state: directory
    mode: '0755'

- name: Clone tfenv
  git:
    repo: https://github.com/tfutils/tfenv.git
    depth: 1
    dest: "$HOME/.tfenv"
    version: "v1.0.1"

- name: Create symbolic links
  file:
    src: "$HOME/.tfenv/bin/{{ item.src }}"
    dest: "$HOME/bin/{{ item.dest }}"
    state: link
  with_items:
    - { src: "tfenv", dest: "tfenv" }
    - { src: "terraform", dest: "terraform" }
