---
- name: User should use zsh
  user:
    name: "{{ ansible_ssh_user }}"
    state: present
    shell: "{{ zsh_path }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: "{{ user_email }}"
  become: yes
