---
- name: OS dependent variables
  set_fact:
    zsh_path: "/usr/local/bin/zsh"

- name: Install zsh
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - zsh
    - reattach-to-user-namespace
