---
- name: OS dependent variables
  set_fact:
    zsh_path: "/usr/bin/zsh"

- name: Install zsh
  pacman:
    name: zsh
    state: present

- name: Install zplug
  aur:
    name: "{{item}}"
    use: yay
    skip_installed: yes
  with_items:
    - zplug
  become_user: aur_builder
  become: yes
