- name: Install wezterm
  vars:
    wezterm_version: "20221119-145034-49b9839f"
  ansible.builtin.apt:
    deb: "https://github.com/wez/wezterm/releases/download/{{ wezterm_version }}/wezterm-{{ wezterm_version }}.Ubuntu20.04.deb"
  become: true
