# https://github.com/Homebrew/homebrew-brewdler
# To install: 
#   $ brew tap Homebrew/brewdler
# Run:
#   $ brew brewdle
brew 'coreutils'
brew 'findutils'
brew 'reattach-to-user-namespace'
brew 'zsh'
brew 'zsh-completions'
brew 'mercurial'
brew 'vim'
brew 'md5sha1sum'
brew 'gist'
brew 'python'
brew 'ruby'
brew 'hicolor-icon-theme'
brew 'gcc'
# brew 'homebrew/x11/scantailor'
brew 'tmux'
brew 'ghostscript'
brew 'tkdiff'
brew 'git'
brew 'pstoedit'
brew 'caskroom/cask/brew-cask'
brew 'peco'
brew 'mackup'
brew 'redis'
brew 'adobe-reader'

# tap 'homebrew/x11'
# brew 'scantailor'

tap 'caskroom/cask'
cask 'box-sync'
cask 'iterm2'
cask 'xquartz'
cask 'mactex'
cask 'dropbox'
cask 'filezilla'
cask 'firefox'
cask 'gimp'
cask 'gitx'
cask 'google-drive'
cask 'skim'
cask 'the-unarchiver'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'evernote'
cask 'magicprefs'
cask 'atom'
cask 'timemachineeditor'
cask 'inkscape'
cask 'googleappengine'
cask 'skype'

tap 'caskroom/homebrew-versions'
cask 'sublime-text3'

tap 'caskroom/fonts'
cask 'font-inconsolata-dz-for-powerline'

