services:
  chromadb:
    image: chromadb/chroma:0.6.3
    ports:
      - "9009:8000"
    volumes:
      - ./.vectorcode_chromadb_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
