---
- name: Check if plugin is installed
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh

    asdf plugin-remove {{ item }}
  args:
    executable: zsh
  changed_when: false
  register: result
  failed_when:
    - result.rc != 0
    - '"No such" not in result.stderr'
  loop: "{{ plugins }}"
