---
- name: Set OS
  vars:
    gotty_oses:
      "elementary OS": "linux"
  set_fact:
    gotty_os: "{{ gotty_oses[ansible_os_family] }}"

- name: Set architecture
  vars:
    gotty_archs:
      x86_64: "amd64"
  set_fact:
    gotty_arch: "{{ gotty_archs[ansible_architecture] }}"

- name: Install binary from GitHub
  vars:
    gotty_version: "1.5.0"
  ansible.builtin.unarchive:
    src: "https://github.com/sorenisanerd/gotty/releases/download/v{{ gotty_version }}/gotty_v{{ gotty_version }}_{{ gotty_os }}_{{ gotty_arch }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/bin"
    remote_src: yes
