---
- name: Clone repository
  vars:
    nf_repo: "github.com/ryanoasis/nerd-fonts"
  ansible.builtin.git:
    repo: "https://{{ nf_repo }}"
    dest: "{{ ansible_env.HOME }}/nerd-fonts"
    depth: 1
    version: v3.2.1
  register: nf_clone_repo

- name: Install font (VictorMono)
  ansible.builtin.command:
    cmd: bash ./install.sh VictorMono
    chdir: "{{ ansible_env.HOME }}/nerd-fonts"
  when: nf_clone_repo.changed

- name: Install font (Iosevka)
  ansible.builtin.command:
    cmd: bash ./install.sh Iosevka
    chdir: "{{ ansible_env.HOME }}/nerd-fonts"
  when: nf_clone_repo.changed

- name: Install font (IosevkaTerm)
  ansible.builtin.command:
    cmd: bash ./install.sh IosevkaTerm
    chdir: "{{ ansible_env.HOME }}/nerd-fonts"
  when: nf_clone_repo.changed
