---
- name: Install gnupg
  community.general.homebrew:
    name: gnupg
    state: present

- name: Install pinentry-mac
  community.general.homebrew:
    name: pinentry-mac
    state: present

- name: Install coreutils
  community.general.homebrew:
    name: coreutils
    state: present
