---
- name: Install stuffs
  homebrew_cask:
    name:
      - google-chrome
      - bitwarden
      - spotify
      - keybase
      - docker
    state: present

- name: Install stuffs (brew)
  homebrew:
    name:
      - docker-compose
    state: present
