---
- name: Install stuffs (pacman)
  pacman:
    name:
      - lxappearance
      - gtk-chtheme
      - pcmanfm-gtk3
      - nitrogen
      - compton
      - docker
      - docker-compose
      - ibus
      - ibus-rime
    state: present
  become: yes

- name: Install stuffs
  aur:
    name:
      - "google-chrome"
      - "pavucontrol"
      - bitwarden-bin
      - spotify
      - keybase-bin
      - nordic-polar-theme-git
      - xcursor-lliurex
      - newaita-icons-git
      - flashfocus-git
      - polybar
      - ibus-mozc
    use: yay
    skip_installed: yes
  become: yes
  become_user: "{{ aur_user }}"

- name: Install steam
  pacman:
    name:
      - steam
      - lib32-libgpg-error
      - lib32-nvidia-utils
    state: present
  become: yes

- name: Start docker
  service:
    name: docker
    enabled: true
    state: started
  become: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    append: yes
    groups:
      - docker
  become: yes
