---
- name: Install stuffs
  aur:
    name:
      - "google-chrome"
      - "pavucontrol"
      - bitwarden-bin
      - spotify
      - keybase-bin
    use: yay
    skip_installed: yes
  become: yes
  become_user: "{{ aur_user }}"

- name: Install steam
  pacman:
    name:
      - steam
      - lib32-libgpg-error
      - lib32-nvidia-utils
    state: present
  become: yes
