---
- homebrew_tap:
    name: homebrew/cask-drivers
    state: present

- name: Install stuffs
  homebrew_cask:
    name:
      - google-chrome
      - bitwarden
      - spotify
      - keybase
      - docker
      - yubico-yubikey-manager
      - notion
    state: present

- name: Install stuffs (brew)
  homebrew:
    name:
      - ykman
    state: present
