---
  - name: Install necessary tools
    pacman: name={{item}} state=latest update_cache=yes
    with_items:
      - stow
      - xclip

  - name: Make user bin directory
    file:
      path: /home/{{ user }}/bin
      state: directory
      mode: 0755
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Download direnv binary
    get_url:
      url: https://github.com/direnv/direnv/releases/download/v2.11.3/direnv.linux-amd64 
      dest: /home/{{ user }}/bin/direnv
      mode: "a+x"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Download pt binary
    get_url:
      url: https://github.com/monochromegane/the_platinum_searcher/releases/download/v2.1.5/pt_linux_amd64.tar.gz
      dest: /tmp/pt.tar.gz

  - name: Install pt binary
    unarchive:
      src: /tmp/pt.tar.gz
      dest: /tmp

  - name: Install pt to user bin
    copy:
      src: /tmp/pt_linux_amd64/pt
      dest: /home/{{ user }}/bin/pt
      mode: "a+x"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Download pet binary
    get_url:
      url: https://github.com/knqyf263/pet/releases/download/v0.2.2/pet_0.2.2_linux_amd64.zip
      dest: /tmp/pet.zip

  - name: Install pet binary
    unarchive:
      src: /tmp/pet.zip
      dest: /home/{{ user }}/bin
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Download peco binary
    get_url:
      url: https://github.com/peco/peco/releases/download/v0.5.1/peco_linux_amd64.tar.gz
      dest: /tmp/peco.tar.gz

  - name: Install peco binary
    unarchive:
      src: /tmp/peco.tar.gz
      dest: /tmp

  - name: Install peco to user bin
    copy:
      src: /tmp/peco_linux_amd64/peco
      dest: /home/{{ user }}/bin/peco
      mode: "a+x"
      owner: "{{ user }}"
      group: "{{ user }}"

  - name: Install zim
    git:
      repo: https://github.com/Eriner/zim.git
      recursive: yes
      dest: /home/{{ user }}/.zim
    become_user: "{{ user }}"

  - name: Install anyframe
    git:
      repo: https://github.com/mollifier/anyframe
      dest: /home/{{ user }}/bin/anyframe
    become_user: "{{ user }}"

  - name: Install dotfiles
    make:
      chdir: /home/{{ user }}/dotfiles
      target: all
    become_user: "{{ user }}"
