scriptencoding utf-8
set nocompatible " Be iMproved, required by vundle.
filetype off     " Required by vundle.

" VUNDLE
" ======
" Set the runtime path to include Vundle and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    
" Let Vundle manage Vundle, required by vundle.
Plugin 'VundleVim/Vundle.vim'

" Color scheme.
Plugin 'jiangmiao/auto-pairs'
Plugin 'sickill/vim-monokai'
Plugin 'altercation/vim-colors-solarized'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-commentary'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'Shougo/neocomplete'
Plugin 'ctrlpvim/ctrlp.vim'

" All plugins must be added before the following line.
call vundle#end()         " Required by vundle.
filetype plugin indent on " Required by vundle.

" Source other settings.
for f in split(glob('~/bin/dotfiles/nvim/vimfiles/*.vim'), '\n')
    exe 'source' f
endfor
