scriptencoding utf-8
set nocompatible " Be iMproved, required by vundle.
filetype off     " Required by vundle.

" VUNDLE
" ======
" Set the runtime path to include Vundle and initialize.
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    
" Let Vundle manage Vundle, required by vundle.
Plugin 'VundleVim/Vundle.vim'

" Color scheme.
Plugin 'jiangmiao/auto-pairs'
Plugin 'chriskempson/vim-tomorrow-theme'
Plugin 'sickill/vim-monokai'
Plugin 'altercation/vim-colors-solarized'
Plugin 'fatih/vim-go'
Plugin 'scrooloose/syntastic'

" All plugins must be added before the following line.
call vundle#end()         " Required by vundle.
filetype plugin indent on " Required by vundle.

" SHORTCUTS
" =========
let mapleader = ","

" SEARCH
" ======
set ignorecase
set hlsearch
set incsearch
set smartcase
set gdefault " s/<find>/<replace>/g -- g is auto-inserted.

" WINDOWS
" =======
set winwidth=84    " ⎤
set winheight=5    " ⎟ Auto resize windows.
set winminheight=5 " ⎟
set winheight=999  " ⎦

" EDITING
" =======
" Indentations.
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Encodings.
set fileencoding=utf-8 " When file is saved.
set encoding=utf-8 " For displaying.

" Brackets.
set showmatch

" Visual.
set list
set listchars=tab:‣\ ,trail:·

" Prevent tab and trail listchars to have highlight in Solarized scheme.
autocmd ColorScheme solarized :hi! link SpecialKey NonText

set number
set cursorline
set cc=80

" Others.
set backspace=indent,eol,start

" COLOR SCHEME
" ============
syntax enable
set background=dark
" Solarized.
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized

" GOLANG (See: https://github.com/fatih/vim-go)
" =============================================
let g:go_highlight_functions = 1         " ⎤
let g:go_highlight_methods = 1           " ⎟ Better highlighting.
let g:go_highlight_structs = 1           " ⎟
let g:go_highlight_operators = 1         " ⎟
let g:go_highlight_build_constraints = 1 " ⎦
let g:go_fmt_command = "goimports"
let g:syntastic_mode_map = { 'mode': 'passive',
    \ 'active_filetypes': ['go'] }
let g:syntastic_go_checkers = ['go', 'golint']
