  - name: Install dependencies
    apt:
      name: "{{item}}"
      state: installed
      update_cache: yes
    with_items:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev 
      - xz-utils
      - tk-dev
