---
- name: Install other utilities (Darwin)
  homebrew:
    name: ["stow", "xclip", "unzip"]
    state: present
  when: ansible_os_family == "Darwin"

- name: Install other utilities (Archlinux)
  pacman:
    name: ["stow", "xclip", "unzip"]
    state: present
  when: ansible_os_family == "Archlinux"
  become: yes
