---
- name: Install NPM packages
  environment:
    NPM_CONFIG_PREFIX: "{{ ansible_env.HOME }}/.npm-global"
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ pkgs }}"

- name: Uninstall
  environment:
    NPM_CONFIG_PREFIX: "{{ ansible_env.HOME }}/.npm-global"
  community.general.npm:
    name: "{{ item }}"
    state: absent
    global: yes
  loop:
    - "@astrojs/language-server"
    - "@fsouza/prettierd"
    - "bash-language-server"
    - "eslint_d"
    - "graphql-language-service-cli"
    - "pyright"
    - "typescript"
    - "typescript-language-server"
    - "vscode-langservers-extracted"
