---
- name: Install go (Darwin)
  homebrew:
    name: ["go"]
    state: present
  when: ansible_os_family == "Darwin"

- name: Install go (Archlinux)
  pacman:
    name: ["go"]
    state: present
  when: ansible_os_family == "Archlinux"
  become: yes
