---
- name: Install go (Darwin)
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - go
  when: ansible_os_family == "Darwin"

- name: Install go (Archlinux)
  pacman:
    name: "{{item}}"
    state: present
  with_items:
    - go
  when: ansible_os_family == "Archlinux"
  become: yes
