---
- name: Install elm
  homebrew:
    name: ["elm"]
    state: present
  when: ansible_os_family == "Darwin"

- name: Install elm
  shell: >
    curl -L https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz | gunzip -c > /usr/local/bin/elm
    warn: no
  args:
    creates: "/usr/local/bin/elm"
  when: ansible_os_family == "Archlinux"
  become: yes

- name: Make elm executable
  file:
    path: /usr/local/bin/elm
    mode: "+x"
  when: ansible_os_family == "Archlinux"
  become: yes
# - name: Install elm-language-server
#   npm:
#     name: "@elm-tooling/elm-language-server"
#     global: yes

# - name: Install elm-test
#   npm:
#     name: "elm-test"
#     global: yes

# - name: Install elm-format
#   npm:
#     name: "elm-format"
#     global: yes
