---
- name: Install elm
  homebrew:
    name: ["elm"]
    state: present
  when: ansible_os_family == "Darwin"

- name: Install elm
  npm:
    name: elm
    global: yes
  when: ansible_os_family == "Archlinux"

- name: Install elm-language-server
  npm:
    name: "@elm-tooling/elm-language-server"
    global: yes

- name: Install elm-test
  npm:
    name: "elm-test"
    global: yes

- name: Install elm-format
  npm:
    name: "elm-test"
    global: yes
