---
- name: Create ngram directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/ngrams"
    state: directory
    mode: "0755"

- name: Download ngram-data
  vars:
    ngram_version: "20150817"
  ansible.builtin.unarchive:
    src: "https://languagetool.org/download/ngram-data/ngrams-en-{{ ngram_version }}.zip"
    dest: "{{ ansible_env.HOME }}/ngrams"
    creates: "{{ ansible_env.HOME }}/ngrams/en"
    remote_src: yes
