---
- name: Remove go
  ansible.builtin.file:
    path: /usr/local/go
    state: absent
  become: true

- name: Remove binaries
  loop:
    - dlv
    - efm-langserver
    - goimports
    - gopls
    - kind
    - sqls
    - checkmake
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go/bin/{{ item }}"
    state: absent
