languages:
  make:
    lint-command: checkmake
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'

  markdown:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
  sh:
    lint-command: 'shellcheck -f tty -'
    lint-stdin: true
