version: 2
root-markers:
  - .git/
tools:
  lua-luafmt: &lua-luafmt
    format-command: "luafmt --stdin -w stdout"
    format-stdin: true

  prettier: &prettier
    format-command: "prettier --stdin-filepath ${INPUT}"
    format-stdin: true

  eslint: &eslint
    lint-command: "eslint -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true
    format-command: "prettier-eslint --stdin --stdin-filepath ${INPUT}"
    format-stdin: true

  pg_format: &pg_format
    format-command: "pg_format -L -"
    format-stdin: true

  rubocop: &rubocop
    lint-command: "rubocop --format emacs"
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c: %m"
    format-command: "rubocop  --stdin FILE -a -f q -o /dev/null | sed '1 d'"
    format-stdin: true

  golangci-lint: &golangci-lint
    lint-command: "golangci-lint run --out-format line-number --print-issued-lines=false"
    lint-ignore-exit-code: true
    lint-stdin: false
    lint-formats:
      - "%f:%l:%c: %m"

  goimports: &goimports
    format-command: "goimports"

languages:
  lua:
    - <<: *lua-luafmt
  javascript:
    - <<: *eslint
    - <<: *prettier
  typescriptreact:
    - <<: *eslint
    - <<: *prettier
  typescript:
    - <<: *eslint
    - <<: *prettier
  json:
    - <<: *prettier
  yaml:
    - <<: *prettier
  markdown:
    - <<: *prettier
  ruby:
    - <<: *rubocop
  sql:
    - <<: *pg_format
  go:
    - <<: *golangci-lint
    - <<: *goimports
  html:
    - <<: *prettier
  css:
    - <<: *prettier
