version: 2
log_file: /home/shihanng/efm.log
log_level: 1
root-markers:
  - .git/
tools:
  lua-luafmt: &lua-luafmt
    format-command: "luafmt --stdin -w stdout"
    format-stdin: true

  prettier: &prettier
    format-command: "prettier --stdin-filepath ${INPUT}"
    format-stdin: true

  eslint: &eslint
    lint-command: "eslint -f unix --stdin"
    lint-ignore-exit-code: true
    lint-stdin: true
    format-command: "prettier-eslint --stdin"
    format-stdin: true

languages:
  lua:
    - <<: *lua-luafmt
  javascript:
    - <<: *eslint
  json:
    - <<: *prettier
  yaml:
    - <<: *prettier
  markdown:
    - <<: *prettier
