---
- name: Install tmux (Darwin)
  homebrew:
    name: tmux
    state: present
  when: ansible_os_family == "Darwin"

- name: Install tmux (Archlinux)
  pacman:
    name: tmux
    state: present
  when: ansible_os_family == "Archlinux"
  become: yes

- name: Install TPM  # https://github.com/tmux-plugins/tpm
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: $HOME/.tmux/plugins/tpm
