---
  - name: Install necessary dependency
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - libevent-dev
      - libncursesw5-dev
      - libncurses5-dev

  - name: Download source
    get_url:
      url: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
      dest: /tmp/tmux.tar.gz

  - name: Unzip
    unarchive:
      src: /tmp/tmux.tar.gz
      dest: /tmp

  - name: Configure
    command: ./configure --prefix=/usr/local
    args:
      chdir: /tmp/tmux-{{ tmux_version }}

  - name: Make
    make:
      chdir: /tmp/tmux-{{ tmux_version }}

  - name: Make install
    make:
      chdir: /tmp/tmux-{{ tmux_version }}
      target: install 

  - name: Install TPM
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: /home/{{ user }}/.tmux/plugins/tpm
    become_user: "{{ user }}"
