---
- name: Install development tools (Darwin)
  homebrew:
    name:
      - awscli
      - direnv
      - fd
      - jq
      - knqyf263/pet/pet
      - moreutils
      - ripgrep
      - kubernetes-cli
      - shellcheck
      - github/gh/gh
      - git-crypt
    state: present
  when: ansible_os_family == "Darwin"

- name: Install development tools (Archlinux)
  pacman:
    name:
      - aws-cli
      - fd
      - jq
      - moreutils
      - ripgrep
      - kubectl
      - shellcheck
      - git-crypt
    state: present
  when: ansible_os_family == "Archlinux"
  become: yes

- name: Install development tools (AUR)
  aur:
    name:
      - direnv
      - pet-bin
      - gh
    use: yay
    skip_installed: yes
  when: ansible_os_family == "Archlinux"
  become: yes
  become_user: "{{ aur_user }}"

- name: Create pet config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/pet"
    state: directory
    mode: 0755

- name: .config/pet/config.toml
  template:
    src: pet_config.j2
    dest: "{{ ansible_env.HOME }}/.config/pet/config.toml"
    backup: no
    mode: 0600
    force: no

# - name: Install docker language server
#   npm:
#     name: "dockerfile-language-server-nodejs"
#     global: yes

# - name: Install bash language server
#   npm:
#     name: "bash-language-server"
#     global: yes

# - name: Install yaml language server
#   npm:
#     name: "yaml-language-server"
#     global: yes

# - name: Install markdownlint-cli
#   npm:
#     name: "markdownlint-cli"
#     global: yes

- name: Install efm-langserver
  shell: GO111MODULE=on go get -u github.com/mattn/efm-langserver@latest
  args:
    creates: ~/go/bin/efm-langserver
# - name: Install vue language server
#   npm:
#     name: "vue-language-server"
#     global: yes

# - name: Install prettier
#   npm:
#     name: "prettier"
#     global: yes
