---
- name: Install development tools (Darwin)
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - direnv
    - ripgrep
    - knqyf263/pet/pet
    - fd
  when: ansible_os_family == "Darwin"

- name: Install development tools (Archlinux)
  pacman:
    name: "{{item}}"
    state: present
  with_items:
    - ripgrep
    - fd
  when: ansible_os_family == "Archlinux"
  become: yes

- name: Install development tools (AUR)
  aur:
    name: "{{item}}"
    use: yay
    skip_installed: yes
  with_items:
    - direnv
    - pet-bin
  when: ansible_os_family == "Archlinux"
  become: yes
  become_user: aur_builder

- name: Create pet config dir
  file:
    path: "$HOME/.config/pet"
    state: directory
    mode: 0755

- name: .config/pet/config.toml
  template:
    src:    pet_config.j2
    dest:   ~/.config/pet/config.toml
    backup: no
    mode:   0600
  become_user: "{{ ansible_user_id }}"
