---
- name: Set OS
  ansible.builtin.set_fact:
    afx_os: "{{ oses[ansible_os_family] }}"

- name: Set architecture
  vars:
    archs:
      x86_64: "x86_64"
  ansible.builtin.set_fact:
    afx_arch: "{{ archs[ansible_architecture] }}"

- name: Download from GitHub
  vars:
    afx_version: "0.1.25"
  ansible.builtin.unarchive:
    src: "https://github.com/b4b4r07/afx/releases/download/v{{ afx_version }}/afx_{{ afx_os }}_{{ afx_arch }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/bin"
    remote_src: true
    creates: "{{ ansible_env.HOME }}/bin/afx"

- name: Create completion
  vars:
    afx_comp_path: "{{ ansible_env.HOME }}/.local/share/zsh/site-functions/_afx"
  args:
    creates: "{{ afx_comp_path }}"
  ansible.builtin.shell: |
    afx completion zsh > {{ afx_comp_path }}
