[General]
  snippetfile = "/Users/shihanng/.config/pet/snippet.toml"
  editor = "nvim"
  column = 40
  selectcmd = "fzf --ansi"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = ""
  gist_id = ""
  auto_sync = true
