---
  - name: Install necessary dependency
    apt:
      name: "{{ item }}"
      state: installed
      update_cache: yes
    with_items:
      - libxcb1-dev
      - libxcb-keysyms1-dev
      - libpango1.0-dev
      - libxcb-util0-dev
      - libxcb-icccm4-dev
      - libyajl-dev
      - libstartup-notification0-dev
      - libxcb-randr0-dev
      - libev-dev
      - libxcb-cursor-dev
      - libxcb-xinerama0-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - autoconf
      - libxcb-xrm0
      - libxcb-xrm-dev
      - dconf-editor
      - rofi
      - i3blocks
      - xcompmgr
      - compton
      - feh

  - name: Download source
    get_url:
      url: https://github.com/Airblader/i3/archive/{{ i3_version }}.tar.gz
      dest: /tmp/i3.tar.gz

  - name: Remove old build directory
    file:
      path: /tmp/i3-{{ i3_version }}
      state: absent

  - name: Unzip
    unarchive:
      src: /tmp/i3.tar.gz
      dest: /tmp

  - name: Run autoreconf
    command: autoreconf --force --install
    args:
      chdir: /tmp/i3-{{ i3_version }}

  - name: Make user bin directory
    file:
      path: /tmp/i3-{{ i3_version }}/build
      state: directory

  - name: Configure
    command: ../configure --prefix=/usr/local --sysconfdir=/etc --disable-sanitizers
    args:
      chdir: /tmp/i3-{{ i3_version }}/build

  - name: Make
    make:
      chdir: /tmp/i3-{{ i3_version }}/build

  - name: Make install
    make:
      chdir: /tmp/i3-{{ i3_version }}/build
      target: install 
