---
- name: Check if plugin is installed
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh

    asdf plugin-list | grep "{{ plugin }}$"
  args:
    executable: zsh
  register: plugin_check_result
  changed_when: false
  ignore_errors: true

- name: Install plugin
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh

    asdf plugin-add {{ plugin }} {{ repo }}
  args:
    executable: zsh
  when: plugin_check_result.rc == 1

- name: Check if a version is installed
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh

    asdf list {{ plugin }} {{ item }}
  args:
    executable: zsh
  loop: "{{ versions }}"
  changed_when: false
  ignore_errors: true
  register: check_install

- name: Install version
  ansible.builtin.shell: |
    source {{ ansible_env.HOME }}/.asdf/asdf.sh

    asdf install {{ plugin }} {{ item.item }}
  args:
    executable: zsh
  when: item.rc == 1
  loop: "{{ check_install.results }}"
