---
- set_fact:
    rose_pine_tmp: /tmp/rose-pine-wezterm

- name: Clone the GitHub repository
  ansible.builtin.git:
    repo: "https://github.com/neapsix/wezterm.git"
    dest: "{{ rose_pine_tmp }}"

- name: Copy the lua/ directory
  ansible.builtin.copy:
    src: "{{ rose_pine_tmp }}/lua/"
    dest: "{{ ansible_env.HOME }}/.config/wezterm/lua/"
