---
- name: Install git, etc. (Darwin)
  homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - git
    - hub
  when: ansible_os_family == "Darwin"

- name: Install git (Archlinux)
  pacman:
    name: "{{item}}"
    state: present
  with_items:
    - git
    - hub
  when: ansible_os_family == "Archlinux"
  become: yes

- name: .gitconfig.local
  template:
    src:    gitconfig.local.j2
    dest:   ~/.gitconfig.local
    backup: no
  become_user: "{{ ansible_user_id }}"
