---
- name: Install git, etc. (Darwin)
  homebrew:
    name: ["git", "hub", "gnupg"]
    state: present
  when: ansible_os_family == "Darwin"

- name: Install git (Archlinux)
  pacman:
    name: ["git", "hub", "gnupg"]
    state: present
  when: ansible_os_family == "Archlinux"
  become: yes

- name: .gitconfig.local
  template:
    src:    gitconfig.local.j2
    dest:   ~/.gitconfig.local
    backup: no
    force: no
  become_user: "{{ ansible_user_id }}"
