---
- name: Add Git stable repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present
  become: true

- name: Install Git
  ansible.builtin.apt:
    name: git
    state: present
  become: true
