---
  - include: arch.yml
    when: ansible_os_family == "Archlinux"

  - include: ubuntu.yml
    when: ansible_os_family == "Debian"

  - name: Make directories for neovim
    file:
      path: ~/{{ item }}
      state: directory
      mode: 0755
    with_items:
      - .local/share/nvim/site/autoload
      - .local/share/nvim/backup
      - .local/share/nvim/swp
      - .local/share/nvim/undo
    become_user: "{{ user }}"

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: ~/.local/share/nvim/site/autoload/
    become_user: "{{ user }}"
