---
  - name: Install dependencies
    apt:
      name: "{{item}}"
      state: installed
      update_cache: yes
    with_items:
      - software-properties-common

  - name: Add neovim PPA
    apt_repository:
      repo: 'ppa:neovim-ppa/stable'
      state: present

  - name: Install neovim
    apt:
      name: neovim
      state: installed
      update_cache: yes
