SELF="${(%):-%N}"
BASEDIR=$(dirname ${SELF:A})

source "${BASEDIR}"/"path.zsh"

if (( $+commands[gdircolors] )); then
  function dircolors {
    local gdc="$(which gdircolors)"
    "${gdc}" "$@"
  }
fi

# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then
  zgen load chrissicool/zsh-256color
  zgen load willghatch/zsh-cdr
  zgen load unixorn/autoupdate-zgen
  zgen load djui/alias-tips
  zgen load zlsun/solarized-man
  zgen load zsh-users/zsh-syntax-highlighting
  zgen load unixorn/tumult.plugin.zsh
  zgen load peterhurford/git-it-on.zsh
  zgen load supercrabtree/k
  zgen load RobSis/zsh-completion-generator
  zgen load joel-porquet/zsh-dircolors-solarized
  zgen load felixr/docker-zsh-completion

  # Prezto's plugins.
  zgen prezto
  zgen prezto 'gnu-utility'
  zgen prezto 'utility'
  zgen prezto 'history'
  zgen prezto 'completion'
  zgen prezto 'spectrum'
  zgen prezto 'git' # TODO(shihanng): Have a look at git-extra.
  zgen prezto 'editor'
  zgen prezto 'prompt' # This should be the last.

  # Prezto's config.
  zgen prezto '*:*' color 'yes'
  zgen prezto 'editor' key-bindings 'vi'
  zgen prezto 'editor' dot-expansion 'yes'
  zgen prezto 'editor:info:completing' format '...'
  zgen prezto 'prompt' theme 'sorin'
  zgen prezto 'git:log:oneline' format '%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'

  # Generate the init script from plugins above
  zgen save
fi

# See zsh-users/zsh-syntax-highlighting.
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)

# For direnv.
eval "$(direnv hook zsh)"
alias tmux='direnv exec / tmux'

for f in "env.zsh" \
  "alias.zsh" \
  "peco.zsh" \
  "proxy.zsh"
do
  if [ -r "${BASEDIR}"/${f} ]; then
    source "${BASEDIR}"/${f}
  fi
done

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
