---
  - name: Download Go from source
    get_url:
      url: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
      dest: /tmp/go{{ go_version }}.linux-amd64.tar.gz

  - name: Unzip and install Go
    unarchive:
      src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
      dest: /usr/local

  - name: Install dependencies for pyenv
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - build-essential
      - module-assistant
      - make
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev

  - name: Install pyenv
    become: no
    shell: wget -O - https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash

  - name: Install rbenv
    become: no
    git:
      repo: https://github.com/rbenv/rbenv.git
      dest: /home/{{ user }}/.rbenv

  - name: Add latest neovim
    apt_repository:
      repo: "ppa:neovim-ppa/unstable"
      state: present

  - name: Install neovim
    apt:
      name: neovim
      update_cache: yes

  - name: Make directories for neovim
    file:
      path: /home/{{ user }}/{{ item }}
      state: directory
      mode: 0755
      owner: "{{ user }}"
      group: "{{ user }}"
    with_items:
      - .local/share/nvim/site/autoload
      - .local/share/nvim/backup
      - .local/share/nvim/swp
      - .local/share/nvim/undo

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/{{ user }}/.local/share/nvim/site/autoload/
