---
- name: Uninstall vim (Archlinux)
  pacman:
    name: vim
    state: absent
  become: yes
  ignore_errors: yes

- name: Install gvim, xdotool (Archlinux)
  pacman:
    name: 
      - gvim
      - xdotool
      - xorg-server
    state: present
  become: yes

- name: Install grip (AUR)
  aur:
    name: "python-grip"
    use: yay
    skip_installed: yes
  become: yes
  become_user: "{{ aur_user }}"
