---
- include: main_darwin.yml
  when: ansible_os_family == "Darwin"

- include: main_archlinux.yml
  when: ansible_os_family == "Archlinux"

- name: Make directories for vim
  file:
    path: "{{ ansible_env.HOME }}/.local/share/vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - site/autoload
    - backup
    - swp
    - undo
