---
  - name: Make directories for vim
    file:
      path: "$HOME/{{ item }}"
      state: directory
      mode: 0755
    with_items:
      - .local/share/vim/site/autoload
      - .local/share/vim/backup
      - .local/share/vim/swp
      - .local/share/vim/undo

  - name: Install neovim (Archlinux)
    pacman:
      name: python-neovim
      state: present
    when: ansible_os_family == "Archlinux"
    become: yes

  - name: install neovim via pip
    pip:
      executable: "/usr/local/bin/pip3"
      name: neovim
      extra_args: --user
    when: ansible_os_family == "Darwin"

  - name: Install vim (Darwin)
    homebrew:
      name: vim
      install_options: "--with-python3"
      state: present
    when: ansible_os_family == "Darwin"

  - name: Install go-langserver
    shell: go get -u github.com/sourcegraph/go-langserver
    args:
      creates: $HOME/go/bin/go-langserver

  - name: Install grip (Darwin)
    homebrew:
      name: "{{item}}"
      state: present
    with_items:
      - grip
    when: ansible_os_family == "Darwin"

  - name: Install xdotool (Archlinux)
    pacman:
      name: "{{item}}"
      state: present
    with_items:
      - xdotool
    become: yes
    when: ansible_os_family == "Archlinux"

  - name: Install grip (AUR)
    aur:
      name: "{{item}}"
      use: yay
      skip_installed: yes
    with_items:
      - python-grip
    when: ansible_os_family == "Archlinux"
    become: yes
    become_user: aur_builder
