---
- hosts: localhost
  become: true
  tasks:
  - name: Add latest git
    apt_repository:
      repo: "ppa:git-core/ppa"
      state: present
  - name: Install git
    apt:
      name: git
      update_cache: yes
