---
- hosts: localhost
  become: true

  vars:
    version: 1.8.1

  tasks:
  - name: Download source
    get_url:
      url: https://storage.googleapis.com/golang/go{{ version }}.linux-amd64.tar.gz
      dest: /tmp/go{{ version }}.linux-amd64.tar.gz

  - name: Unzip
    unarchive:
      src: /tmp/go{{ version }}.linux-amd64.tar.gz
      dest: /usr/local
