---
- hosts: localhost
  become: true
  tasks:
  - name: Install build-essential and module-assistant
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - build-essential
      - module-assistant
  - name: Configure system for building kernel modules
    shell: m-a prepare
  - name: Mount Guest Additions CD
    mount:
      name: /tmp/vbox
      src: /dev/sr0
      opts: loop
      fstype: iso9660
      state: mounted
  - name: Run install script
    script: /tmp/vbox/VBoxLinuxAdditions.run
  - name: Unmount Guest Additions CD
    mount:
      name: /tmp/vbox
      src: /dev/sr0
      fstype: iso9660
      state: absent
