---
- hosts: localhost
  vars:
    user: shihanng

  tasks:
  - name: Make directories
    file:
      path: /home/{{ user }}/{{ item }}
      state: directory
      mode: 0755
    with_items:
      - .local/share/nvim/site/autoload
      - .local/share/nvim/backup
      - .local/share/nvim/swp
      - .local/share/nvim/undo

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/{{ user }}/.local/share/nvim/site/autoload/
