---
- include: ./pyenv.yml
- hosts: localhost
  vars:
    user: shihanng
    py2ver: 2.7.13
    py3ver: 3.6.1

  tasks:

  - name: Make directories
    file:
      path: /home/{{ user }}/{{ item }}
      state: directory
      mode: 0755
    with_items:
      - .local/share/nvim/site/autoload
      - .local/share/nvim/backup
      - .local/share/nvim/swp
      - .local/share/nvim/undo

  - name: Install vim-plug
    get_url:
      url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      dest: /home/{{ user }}/.local/share/nvim/site/autoload/

  - name: Install neovim
    shell: |
      pyenv install -s {{ py2ver }}
      pyenv install -s {{ py3ver }}
      pyenv uninstall -f neovim2
      pyenv uninstall -f neovim3
      pyenv virtualenv -f {{ py2ver }} neovim2
      pyenv virtualenv -f {{ py3ver }} neovim3
      pyenv activate neovim2
      pip install neovim
      pyenv activate neovim3
      pip install neovim flake8
      ln -s `pyenv which flake8` /home/{{ user }}/bin/flake8
