---
- hosts: all
  roles:
    - role: terminal
    - role: yay
      when: ansible_os_family == "Archlinux"
    - role: zsh
    - role: tmux
    - role: git
    - role: utils
    - role: golang
    - role: python
    - role: node
    - role: ruby
    - role: devtools
    - role: fonts
    - role: terraform
    - role: wm
    - role: vim
      tags: runme
