---
- hosts: all
  roles:
    - fubarhouse.golang
    - kewlfft.aur
    - role: terminal
    - role: yay
      when: ansible_os_family == "Archlinux"
    - role: zsh
    - role: tmux
    - role: git
    - role: utils
    - role: golang
    - role: ruby
    - role: elm
    - role: devtools
    - role: fonts
    - role: terraform
    - role: wm
    - role: vim
    - role: daily
      tags: runme
