---
- hosts: all
  roles:
    - role: yay
      tags: runme
    - role: zsh
    - terminal
    - tmux
    - git
    - utils
    - golang
    - devtools
    - python
    - ruby
    - node
    - fonts
    - vim
    - terraform
    - role: wm
      when: ansible_os_family == "Archlinux"
