---
- name: Talk to all hosts just so we can learn about them
  hosts: all
  vars:
    distro: "{{ ansible_facts['distribution'] | replace(' ', '_') | lower }}"
  # Handling OS and distro differences, see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#handling-os-and-distro-differences
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: "os_{{ distro }}"
      changed_when: false

  roles:
    - git
    - asdf
    - role: asdf_install
      plugin: tflint
      repo: https://github.com/skyzyx/asdf-tflint
      versions:
        - "0.42.2"
        - "0.43.0"
    - role: asdf_install
      plugin: terraform-ls
      repo: https://github.com/shihanng/asdf-terraform-ls
      versions: 
        - "0.30.0"
