---
- name: Talk to all hosts just so we can learn about them
  hosts: all
  vars:
    distro: "{{ ansible_distribution | replace(' ', '_') | lower }}"
    archs:
      x86_64: "amd64"
    oses:
      "elementary OS": "linux"
      "Darwin": "darwin"

  # Handling OS and distro differences, see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#handling-os-and-distro-differences
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: "os_{{ distro }}"
      changed_when: false

  roles:
    - tar
    - git
    - asdf

    - role: asdf_install
      plugin: tflint
      repo: https://github.com/skyzyx/asdf-tflint
      versions:
        - "0.42.2"
        - "0.43.0"
    - role: asdf_install
      plugin: terraform-ls
      repo: https://github.com/asdf-community/asdf-hashicorp.git
      versions:
        - "0.30.0"
    - role: asdf_install
      plugin: terraform
      repo: https://github.com/asdf-community/asdf-hashicorp.git
      versions:
        - "1.3.5"

    - role: gh

    - role: asdf_install
      plugin: nodejs
      repo: https://github.com/asdf-vm/asdf-nodejs.git
      versions:
        - "18.12.1"

    - role: asdf_install
      plugin: python
      repo: https://github.com/asdf-community/asdf-python
      versions:
        - "3.11.0"
        - "3.10.8"
        - "3.9.15"
        - "3.8.15"

    - role: asdf_install
      plugin: ruby
      repo: https://github.com/asdf-vm/asdf-ruby.git
      versions:
        - "3.0.2"

    - role: asdf_install
      plugin: erlang
      repo: https://github.com/asdf-vm/asdf-erlang.git
      versions:
        - "25.2"

    - role: asdf_install
      plugin: elixir
      repo: https://github.com/asdf-vm/asdf-elixir.git
      versions:
        - "1.14.2"

    - role: asdf_pyapp
      plugins:
        - name: black
          versions:
            - "22.10.0"
        - name: isort
          versions:
            - "5.10.1"
        - name: flake8
          versions:
            - "6.0.0"
        - name: mypy
          versions:
            - "0.991"
        - name: pipenv
          versions:
            - "2022.12.19"
        - name: aws-sso-util
          versions:
            - "4.30.0"

    - role: asdf_install
      plugin: poetry
      repo: https://github.com/asdf-community/asdf-poetry.git
      versions:
        - "1.2.2"

    - role: asdf_install
      plugin: ghq
      repo: https://github.com/kajisha/asdf-ghq
      versions:
        - "1.3.0"

    - role: asdf_install
      plugin: helm
      repo: https://github.com/Antiarchitect/asdf-helm.git
      versions:
        - "3.10.3"

    - role: go
      go_version: "1.19.3"
      go_installs:
        # - "github.com/lighttiger2505/sqls@latest"
        # - "github.com/mattn/efm-langserver@latest"
        # - "golang.org/x/tools/cmd/goimports@latest"
        # - "golang.org/x/tools/gopls@latest" -- Uninstalled
        # - "sigs.k8s.io/kind@v0.17.0"
        - "github.com/mrtazz/checkmake/cmd/checkmake@latest"

    - role: asdf_remove
      plugins:
        - "awscli"
        - "direnv"
        - "kustomize"
        - "lua"
        - "pgcli"

    - role: fzf

    - role: keybase

    - role: tpm

    - role: gnupg

    - role: fd

    - role: delta

    - role: golangci-lint

    - role: tmuxp

    - role: ccls

    - role: pandoc # We need this for checkmake

    - role: clang-format

    - role: github-labeler

    - role: gotty

    - role: rose-pine

    - role: wezterm

    - role: ngram-data

    - role: npm_install # This is actually uninstall

    - role: lua # Mostly uninstalled

    - role: uninstall
