---
- name: Talk to all hosts just so we can learn about them
  hosts: all
  vars:
    distro: "{{ ansible_facts['distribution'] | replace(' ', '_') | lower }}"
    archs:
      x86_64: "amd64"
    oses:
      "elementary OS": "linux"
      "Darwin": "darwin"

  # Handling OS and distro differences, see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#handling-os-and-distro-differences
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: "os_{{ distro }}"
      changed_when: false

  roles:
    - git
    - asdf

    - role: asdf_install
      plugin: tflint
      repo: https://github.com/skyzyx/asdf-tflint
      versions:
        - "0.42.2"
        - "0.43.0"
    - role: asdf_install
      plugin: terraform-ls
      repo: https://github.com/asdf-community/asdf-hashicorp.git
      versions:
        - "0.30.0"
    - role: asdf_install
      plugin: terraform
      repo: https://github.com/asdf-community/asdf-hashicorp.git
      versions:
        - "1.3.5"

    - role: asdf_install
      plugin: direnv
      repo: https://github.com/asdf-community/asdf-direnv
      versions:
        - "2.32.2"

    - role: gh

    - role: asdf_install
      plugin: nodejs
      repo: https://github.com/asdf-vm/asdf-nodejs.git
      versions:
        - "18.12.1"
    - role: npm_install
      pkgs:
        - "@bitwarden/cli"
        - "@fsouza/prettierd"
        - "eslint_d"
        - "pyright"
        - "yarn"

    - role: asdf_install
      plugin: python
      repo: https://github.com/asdf-community/asdf-python
      versions:
        - "3.11.0"
        - "3.10.8"
        - "3.9.15"
        - "3.8.15"

    - role: asdf_pyapp
      plugins:
        - name: black
          versions:
            - "22.10.0"
        - name: isort
          versions:
            - "5.10.1"
        - name: flake8
          versions:
            - "6.0.0"
        - name: mypy
          versions:
            - "0.991"

    - role: asdf_install
      plugin: poetry
      repo: https://github.com/asdf-community/asdf-poetry.git
      versions:
        - "1.2.2"

    - role: asdf_install
      plugin: awscli
      repo: https://github.com/MetricMike/asdf-awscli.git
      versions:
        - "2.9.3"

    - role: asdf_install
      plugin: ghq
      repo: https://github.com/kajisha/asdf-ghq
      versions:
        - "1.3.0"

    - role: go
      go_version: "1.19.3"
      go_installs:
        - "github.com/mattn/efm-langserver@latest"
        - "golang.org/x/tools/gopls@latest"

    - role: fzf

    - role: lua

    - role: keybase

    - role: tpm

    - role: gnupg

    - role: pet

    - role: fd

    - role: delta

    - role: golangci-lint
