---
- name: Talk to all hosts just so we can learn about them
  hosts: all
  vars:
    distro: "{{ ansible_distribution | replace(' ', '_') | lower }}"
    archs:
      x86_64: "amd64"
      arm64: "arm64"
    oses:
      "elementary OS": "linux"
      "Darwin": "darwin"

  # Handling OS and distro differences, see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#handling-os-and-distro-differences
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: "os_{{ distro }}"
      changed_when: false

  roles:
    - tar
    - git

    - role: gh

    - role: go
      go_version: "1.20.1"
      go_installs:
        # - "github.com/lighttiger2505/sqls@latest"
        # - "github.com/mattn/efm-langserver@latest"
        # - "golang.org/x/tools/cmd/goimports@latest"
        # - "golang.org/x/tools/gopls@latest" -- Uninstalled
        # - "sigs.k8s.io/kind@v0.17.0"
        - "github.com/mrtazz/checkmake/cmd/checkmake@latest"

    - role: fzf

    - role: keybase

    - role: tpm

    - role: gnupg

    - role: fd

    - role: golangci-lint

    - role: ccls

    - role: pandoc # We need this for checkmake

    - role: clang-format

    - role: gotty

    - role: rose-pine

    - role: wezterm

    - role: ngram-data

    - role: afx

    - role: ripgrep

    - role: rustup

    - role: starship

    - role: navi

    - role: nerdfont

    - role: npm_install # This is actually uninstall

    - role: lua # Mostly uninstalled

    - role: uninstall

    - role: yabai

    - role: tree
