vim.opt.shell = "/bin/bash"

require("shihanng.basic")
require("shihanng.remap")
require("shihanng.motion")
require("shihanng.aesthetic")
require("shihanng.explore")
require("shihanng.format")
require("shihanng.spell")
require("shihanng.browser")
require("shihanng.test")
require("shihanng.quickfix")
require("shihanng.git")
require("shihanng.git_wp")
require("shihanng.tf")
require("shihanng.multi")
