aws:
    variables:
        - name: aws_key_id
          description: something
          default:
        - name: aws_secret
          description: something secret
          default:
        - name: aws_region
          description: something region
          default:
    template: |
        export AWS_ACCESS_KEY_ID={{ aws_key_id }}
        export AWS_SECRET_ACCESS_KEY={{ aws_secret }}
        export AWS_DEFAULT_REGION={{ aws_region }}
