---
  - name: Install dependencies
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items:
      - git
      - stow
      - xclip
      - unzip
      - make

  - name: Install zplug
    git:
      repo: https://github.com/zplug/zplug
      dest: ~/.zplug
    become: no
