# load zgen
source "${HOME}/.zgen/zgen.zsh"

# if the init scipt doesn't exist
if ! zgen saved; then

  zgen load zlsun/solarized-man
  zgen load zsh-users/zsh-syntax-highlighting

  # Prezto's plugins.
  zgen prezto
  zgen prezto 'git' # TODO(shihanng): Have a look at git-extra.
  zgen prezto 'editor'
  zgen prezto 'prompt' # This should be the last.

  # Prezto's config.
  zgen prezto '*:*' color 'yes'
  zgen prezto 'editor' key-bindings 'vi'
  zgen prezto 'editor' dot-expansion 'yes'
  zgen prezto 'editor:info:completing' format '...'
  zgen prezto 'prompt' theme 'sorin'

  # Generate the init script from plugins above
  zgen save
fi

# These was in omz.
# (brew go golang docker vagrant tmux tmuxinator gitfast)

# Source my settings.
source ~/bin/dotfiles/zsh/env
source ~/bin/dotfiles/zsh/alias

# Source proxy.
if [ -f ~/bin/dotfiles/zsh/proxy ];
then
    source ~/bin/dotfiles/zsh/proxy
fi

# Search shell history with peco: https://github.com/peco/peco
# Adapted from: https://github.com/mooz/percol#zsh-history-search
if which peco &> /dev/null; then
  function peco_select_history() {
    local tac
    if which gtac &> /dev/null; then
        tac="gtac"
    elif which tac &> /dev/null; then
        tac="tac"
    else
        tac="tail -r"
    fi
    BUFFER=$(fc -l -n 1 | eval $tac | \
                peco --layout=bottom-up --query "$LBUFFER")
    CURSOR=$#BUFFER # move cursor
    zle -R -c       # refresh
  }

  zle -N peco_select_history
  bindkey '^R' peco_select_history
fi

# See zsh-users/zsh-syntax-highlighting.
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor root line)

# For direnv.
eval "$(direnv hook zsh)"
alias tmux='direnv exec / tmux'
