- name: Fetch Navi
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/denisidoro/navi/master/scripts/install
    return_content: true
    creates: "{{ ansible_env.HOME }}/bin/navi"
  register: fetch_navi

- name: Run Navi installer
  ansible.builtin.shell:
    cmd: BIN_DIR={{ ansible_env.HOME }}/bin bash -s
    stdin: "{{ fetch_navi.content }}"
    creates: "{{ ansible_env.HOME }}/bin/navi"
  when: fetch_navi.content is defined
