---
- name: Include tasks for {{ distro }}
  ansible.builtin.include_tasks: os_{{ distro }}.yml

- name: Ensure binary not installed
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin/{{ item }}"
    state: absent
  loop:
    - lazygit
