---
- name: "Ensure package not installed via homebrew"
  community.general.homebrew:
    name: "{{ item }}"
    state: absent
  loop:
    - ansible
    - jesseduffield/lazygit/lazygit
    - knqyf263/pet/pet
    - kustomize
  ignore_errors: yes
