---
- name: Install nerd-fonts repo
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: $HOME/nerd-fonts
    version: 2.0.0

- name: Decide on font
  set_fact:
    font_name: "FantasqueSansMono"

- name: Font path
  set_fact:
    font_path: "$HOME/.local/share/fonts/NerdFonts/Fantasque*"
  when: ansible_os_family == "Archlinux"

- name: Install font
  shell: "$HOME/nerd-fonts/install.sh {{ font_name }}"
  args:
    creates: "{{ font_path }}"
