---
- name: Include task list in play
  vars:
    plugin: tflint
    repo: https://github.com/skyzyx/asdf-tflint
    version: "0.43.0"
  ansible.builtin.include_tasks:
    file: ../../../tasks/asdf.yml
